### ISSUE TITLE
Garbled hints in the message trees

### ISSUE THREAD

**Issue by IL2** [graemeg/xananews#3]
XanaNews 1.19.1.372
Hints in any column in the message tree are garbled for me.
![clipboard01](https://cloud.githubusercontent.com/assets/1766789/4525655/4ee3506c-4d56-11e4-9ed9-82a1380677c9.png)

**Comment by graemeg** [comment]
This was a bug in VirtualTreeView and has been resolved in the 1.20 release.

**Comment by IL2** [comment]
Yep, no bug in 1.20. Thank you.
