### ISSUE TITLE
"File | Exit" menu does not exit the app

### ISSUE THREAD

**Issue by rlebeau** [graemeg/xananews#7]
Clicking on the "X" button in the top-right corner, or right-clicking on the main window's Taskbar button and choosing "Close window", will not actually exit the app, it just minimizes to a System Tray icon.  Fine, many apps do that.

But, when in the main window, going to the "File" menu and choosing "Exit" does the SAME THING - NOT OK!

The only way to actually exit the app is to right-click on the System Tray icon and choose "Exit XanaNews".

**Comment by graemeg** [comment]
Thanks for reporting the issue. It has been fixed in commit baae45f624a and will be available in the next release. Alternatively, you can build XanaNews yourself (“develop” branch) and benefit from the fix immediately.
